// Generated by CoffeeScript 1.3.3
(function() {

  describe('Initialize App', function() {
    it('App Start shoud be defined', function() {
      return expect(App.Start).toBeDefined();
    });
    return it('App Start constructor shoul return true', function() {
      return expect(App.Start()).toBeTruthy();
    });
  });

}).call(this);
