// Generated by CoffeeScript 1.3.3
(function() {

  window.App = {};

  App.Start = (function() {

    function Start(attributes) {
      this.attributes = attributes;
      if (typeof jQuery !== 'undefined') {
        $('html').removeClass('no-js');
        $(document).ready(function() {
          return console.log('Document is ready!');
        });
      }
      return true;
    }

    return Start;

  })();

}).call(this);
